export default {
    "1password": "1Password",
    "abnormal": "Abnormal AI",
    "atlassian": "Atlassian",
    "auth0": "Auth0",
    "authentik": "Authentik",
    "backfill": "Backfill",
    "aws": "AWS",
    "azure": "Azure",
    "bitwarden": "Bitwarden",
    "box": "BOX",
    "circleci": "CircleCI",
    "cloudentity": "Cloudentity",
    "cloudflare": "Cloudflare",
    "crowdstrike": "CrowdStrike",
    "cyberhaven": "Cyberhaven",
    "dnsfilter": "DNSFilter",
    "dope-security": "Dope Security",
    "dropbox": "Dropbox",
    "duo": "Duo Security",
    "fastly-waf": "Fastly WAF",
    "firehydrant": "FireHydrant",
    "fluent-bit": "Fluent Bit",
    "formal-security": "Formal Security",
    "gcp": "GCP",
    "generic": "Generic Sources",
    "github": "GitHub",
    "gitlab": "GitLab",
    "google-workspace-logs": "Google Workspace",
    "hashicorp-vault": "HashiCorp Vault",
    "heroku": "Heroku",
    "jamf": "JAMF",
    "jamfprotect": "JAMF Protect",
    "jumpcloud": "JumpCloud",
    "keeper": "Keeper Security",
    "kubernetes": "Kubernetes Audit Logs",
    "linear": "Linear",
    "lumos": "Lumos",
    "mongodb": "MongoDB",
    "notion": "Notion",
    "obsidian-security": "Obsidian Security",
    "okta": "Okta",
    "opal": "Opal",
    "pagerduty": "PagerDuty",
    "palo-pano-traffic": "Palo Alto Panorama Traffic",
    "reveald": "Reveald",
    "sentinelone": "SentinelOne",
    "slack": "Slack",
    "snowflake": "Snowflake",
    "sophos": "Sophos",
    "structured-webhooks": "Structured Webhooks",
    "tailscale": "Tailscale",
    "teleport": "Teleport Cloud Audit Logs",
    "twingate": "Twingate",
    "webflow-audit": "Webflow",
    "wiz-threats": "Wiz Threats",
    "workday": "Workday",
    "zendesk": "Zendesk"
}
