export default {
    "1password": "1Password",
    "atlassian": "Atlassian",
    "auth0": "Auth0",
    "aws": "AWS",
    "azure": "Azure",
    "bitwarden": "Bitwarden",
    "cloudentity": "Cloudentity",
    "cloudflare": "Cloudflare",
    "crowdstrike": "CrowdStrike",
    "cyberhaven": "Cyberhaven",
    "dnsfilter": "DNSFilter",
    "dropbox": "Dropbox",
    "fastly-waf": "Fastly WAF",
    "fluent-bit": "Fluent Bit",
    "gcp": "GCP",
    "generic": "Generic Sources",
    "github": "GitHub",
    "gitlab": "GitLab",
    "google-workspace-logs": "Google Workspace",
    "jamf": "JAMF",
    "jamfprotect": "JAMF Protect",
    "jumpcloud": "JumpCloud",
    "keeper": "Keeper Security",
    "kubernetes": "Kubernetes Audit Logs",
    "mongodb": "MongoDB",
    "notion": "Notion",
    "obsidian-security": "Obsidian Security",
    "okta": "Okta",
    "opal": "Opal",
    "pagerduty": "PagerDuty",
    "palo-pano-traffic": "Palo Alto Panorama Traffic",
    "reveald": "Reveald",
    "sentinelone": "SentinelOne",
    "slack": "Slack",
    "sophos": "Sophos",
    "structured-webhooks": "Structured Webhooks",
    "tailscale": "Tailscale",
    "teleport": "Teleport Cloud Audit Logs",
    "wiz-threats": "Wiz Threats",
    "zendesk": "Zendesk"
}
