#!/usr/bin/env node

/**
 * Generate TypeScript types from sources.json schema
 * 
 * This script generates TypeScript type definitions from the JSON schema
 * to provide type safety for consumers of sources.json
 */

const fs = require('fs');
const path = require('path');

const SCHEMA_PATH = path.join(__dirname, 'sources-schema.json');
const OUTPUT_PATH = path.join(__dirname, '../data/sources.d.ts');

function generateTypes() {
  const schema = JSON.parse(fs.readFileSync(SCHEMA_PATH, 'utf-8'));
  
  const sourceProperties = schema.properties.sources.items.properties;
  
  let typeDef = `/**
 * Auto-generated TypeScript types for sources.json
 * Generated from sources-schema.json
 * 
 * DO NOT EDIT THIS FILE MANUALLY
 * Run: node scripts/generate-types.js
 */

export interface Source {
  id: string;
  name: string;
  description: string;
  logo: string;
  url: string;
  ingestTypes?: ${sourceProperties.ingestTypes.items.enum.map(e => `"${e}"`).join(' | ')};
  categories?: string[];
  tableName?: string[];
  plan?: "free" | "pro" | "ent";
}

export interface SourcesData {
  generatedAt: string;
  sourceCount: number;
  sources: Source[];
}

declare const sourcesData: SourcesData;
export default sourcesData;
`;

  fs.writeFileSync(OUTPUT_PATH, typeDef);
  console.log(`✅ Generated TypeScript types: ${OUTPUT_PATH}`);
}

if (require.main === module) {
  generateTypes();
}

module.exports = { generateTypes };
